name: Опечатка
description: Если вы нашли досадную опечатку.
title: "[Опечатка] "
labels: [ "Статус: Требуется проверка" ]
assignees:
  - saundefined
body:
  - type: input
    id: url
    attributes:
      label: Страница с ошибкой
      description: Пожалуйста, укажите адрес страницы с опечаткой.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Описание ошибки
      description: Пожалуйста, опишите, как нам найти опечатку на странице.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Ваш вариант перевода
      description: При желании, можете указать свой вариант перевода.
    validations:
      required: false
