name: Ошибка перевода
description: Если перевод отличается от оригинальной версии.
title: "[Ошибка перевода] "
labels: [ "Статус: Требуется проверка", "Статус: Ошибка перевода" ]
assignees:
  - saundefined
body:
  - type: input
    id: url
    attributes:
      label: Страница с опечаткой
      description: Пожалуйста, укажите адрес страницы с ошибкой.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Описание ошибки
      description: Пожалуйста, опишите, как нам найти ошибку на странице.
    validations:
      required: true

  - type: textarea
    id: suggsetion
    attributes:
      label: Ваш вариант перевода
      description: При желании, укажите ваш вариант перевода.
    validations:
      required: false
