name: Check Russian build

on: [ push, pull_request ]

jobs:
  check-build:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Russian module
        uses: actions/checkout@master
        with:
          path: 'ru'

      - name: Fetch English module
        uses: actions/checkout@master
        with:
          repository: 'php/doc-en'
          path: 'en'

      - name: Fetch base module
        uses: actions/checkout@master
        with:
          repository: 'php/doc-base'
          path: 'doc-base'

      - name: Check build
        run: php doc-base/configure.php --with-lang=ru